### ISSUE TITLE
psmovepair runtime error : "ioctl (GFEATURE): No such device" on Ubuntu 14.04

### ISSUE THREAD

**Issue by Babouchot** [thp/psmoveapi#108]
Hi all,

I'm facing an ioctl error when trying to run the command psmovepair as well as when running "example" or any other USB related command. I read on a google group thread that it may be a kernel related issue but in the concerned topic the problem was an old version of the kernel. Here I specially installed the latest version of Ubuntu (14.04 LTS) for the psmoveapi and compiled it without troubles. Here is the output :

	babouchot@babouchot-N750JV:~/workspace/psmoveapi/build$ sudo ./psmovepair 
	Connected controllers: 1
	ioctl (GFEATURE): No such device
	ioctl (GFEATURE): No such device
	psmovepair: /home/babouchot/workspace/psmoveapi/src/psmove.c:915: _psmove_get_calibration_blob: Assertion `res == 49' failed.
	babouchot@babouchot-N750JV:~/workspace/psmoveapi/build$ uname -a
	Linux babouchot-N750JV 3.13.0-27-generic #50-Ubuntu SMP Thu May 15 18:06:16 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
	babouchot@babouchot-N750JV:~/workspace/psmoveapi/build$ lsusb 
	Bus 002 Device 002: ID 8087:8000 Intel Corp. 
	Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
	Bus 001 Device 002: ID 8087:8008 Intel Corp. 
	Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
	Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
	Bus 003 Device 005: ID 13d3:5188 IMC Networks 
	Bus 003 Device 004: ID 13d3:3402 IMC Networks 
	Bus 003 Device 007: ID 054c:03d5 Sony Corp. PlayStation Move motion controller
	Bus 003 Device 002: ID 1415:2000 Nam Tai E&E Products Ltd. or OmniVision Technologies, Inc. Sony Playstation Eye
	Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

Maybe my Ubuntu/kernel version is to recent because I also installed it almost the same way on an Ubuntu 12.04 virtual machine and didn't face this problem (but so many weird others :p).

Do you have any idea on how to solve the problem ?

**Comment by nitsch** [comment]
BTW, this table

  http://people.canonical.com/~kernel/info/kernel-version-map.html

maps Ubuntu's kernel versions to the mainline versions.

**Comment by thp** [comment]
Fixed.
