### ISSUE TITLE
psmove_poll returning buffered, rather than current frame

### ISSUE THREAD

**Issue by evanbrumley** [thp/psmoveapi#122]
Hey all,

I've been having some issues with the psmove_poll function - basically, where previously I would always get the current state of the move controller, I now seem to be getting the next in a list of frames buffering around 71hz.

For instance, if I run `examples/psmove_test.py`, which polls at 10hz by default, I end up with a ~7 second lag while it 'catches up'. This lag can be eliminated by upping the polling frequency to just above 71hz (i.e. `sleep(0.014)`)

I'm running a fresh install of Ubuntu 12.04, with one caveat - I have the beta of Johann Sebastian Joust installed. Is it possible that may have flipped a bluetooth setting somewhere, causing this buffering? I imagine they would be very keen to avoid missed frames!

Kind regards,

Ev

**Comment by thp** [comment]
Can this be closed? I think so, if not please re-open.
