### ISSUE TITLE
Navigation Controller not detected

### ISSUE THREAD

**Issue by tnbeatty** [thp/psmoveapi#133]
When plugging in a navigation controller via USB and running `./examples` or `./psmovepair`, I get the following output:

Connected controllers: 0

I have tried searching through the code - I can't figure out why the controller wouldn't be found. I am on a Mac running os x 9.5. Any help much appreciated! I'll keep looking into it.

**Comment by thp** [comment]
Closing this in favor of #185, which already contains some more details.
