### ISSUE TITLE
some issue in cl-eye sdk and test_tracker

### ISSUE THREAD

**Issue by zhaowanqing** [thp/psmoveapi#143]
Thank all who contributed to this great library,It  narrow the gap between the VR!
when i enjoy the library and use it do some thing,there are some issue puzzle me serious. 
so i want get your support,thanks!
first,i find the pseye not work in psmoveapi-64,i only can open it in psmoveapi-32,but when i test the 
test_tracker ,it don`t work like the video,the Box jumps randomly and the move Controller led didn`t bright. The concole printf “no lens calibration”,and i find in code because lack intrinsics.xml and distortion.xml,but how to get it.
second, when i run the test_tracker ,the psmove can`t keep bright when controller calibration end. 
I think this is may be the problem of pseye driver ,so i download the cl-eye sdk and install it. But when i recompile the psmoveapi ,it also can`t find sdk. I find it need CLEyeMulticam.dll ,but there isn`t the file in CL-Eye Platform SDK.
Thanks more suppot for me!

**Comment by thp** [comment]
Closing this. CL Eye SDK not supported anymore. Use CL Eye Driver (via OpenCV) or PSEYEDriver instead.
