### ISSUE TITLE
C# Bindings AccessViolationException

### ISSUE THREAD

**Issue by myacxy** [thp/psmoveapi#144]
Accessing e.g. `psmoveapi_csharpPINVOKE.psmove_get_serial(PSMove.getCPtr(move))` causes an `AccessViolationException`.
#### Additions

I am neither very familiar with SWIG nor C so I just made some sluggish additions.
##### PSMove.c

``` c
void
get_serial(PSMove *move, char *serial)
{
    strcpy(serial, move->serial_number);
}
```
##### PSMove.h

``` c
ADDAPI void
ADDCALL get_serial(PSMove *move, char *serial);
```
#### SWIG output

SWIG produces some output that way but running it will still cause an `Exception`.
##### psmoveapi_csharp.cs

``` csharp
public static void get_serial(PSMove move, string serial) {
    psmoveapi_csharpPINVOKE.get_serial(PSMove.getCPtr(move), serial);
}
```
##### psmoveapi_csharpPINVOKE.cs

``` csharp
[DllImport("psmoveapi_csharp", EntryPoint="CSharp_get_serial")]
public static extern void get_serial(HandleRef jarg1, string jarg2);
```
#### Modifications

I tried to modify the SWIG interface but could not produce any outcome that does not need further attention so I manually made some adjustments.
##### psmoveapi_csharpPINVOKE.cs

``` csharp
[DllImport("libpsmoveapi_csharp", EntryPoint = "CSharp_get_serial@8")]
public static extern void get_serial(HandleRef jarg1, StringBuilder jarg2);
```
##### PSMove.cs

``` csharp
public string get_serial()
{
    StringBuilder builder = new StringBuilder(32);
    pinvoke.get_serial(move, builder);
    return builder.ToString();
}
```
#### Reading Material

[Swig Documentation](http://www.swig.org/Doc3.0/SWIGDocumentation.html)
[Turning output arg char to StringBuilder](http://swig.10945.n7.nabble.com/Turning-output-arg-char-to-StringBuilder-in-C-td4208.html)
[Swig Chatbot](http://vinterstitial.blogspot.de/2014/05/a-swig-of-chatbot-making-unity-chatter.html)

**Comment by thp** [comment]
Closing this for now, if somebody wants to pick this up, feel free to send a pull request.
