### ISSUE TITLE
I have a Problem in Yosemite OS

### ISSUE THREAD

**Issue by mauricioduqueorozco** [thp/psmoveapi#177]
Dear i have a problem with pairing te motion controller ps3, on mac Yosemite, maybe your API support this?
I have many information for this.
Thanks!!

**Comment by alejost848** [comment]
I'm also using Yosemite and it works fine. I just followed this set of instructions https://docs.google.com/document/d/16oB5jpbCpeRWb0o7w0b9bFbT3vEzWGqEPESWZUSCPuU/edit

**Comment by thp** [comment]
Closing this as fixed. PS Move API works when built from source on OS X Yosemite and even El Capitan.
