### ISSUE TITLE
Error bulid psmoveapi_tracker

### ISSUE THREAD

**Issue by czhzng** [thp/psmoveapi#189]
I have this error under MSVC 2013.

fatal error C1083: Cannot open include file: 'ps3eyedriver.h': No such file or directory

where can i found it?

thanks!

**Comment by thp** [comment]
Did you do a `git clone --recursive` or `git submodule init && git submodule update`?

**Comment by czhzng** [comment]
yes, I do.
in project "psmoveapi_tracker", I defined CAMERA_CONTROL_USE_PS3EYE_DRIVER.

**Comment by cboulay** [comment]
It was my fault. He/she was using my fork. It's too bad github doesn't allow issues on forks.

I had a dangling reference to a submodule that was preventing the --recursive or init && update from completing.

**Comment by thp** [comment]
Ok, I guess I can close this as working now? :)

**Comment by thp** [comment]
Closing. Please reopen if there's still something I can do to help here.
