### ISSUE TITLE
“Building the API manually”

### ISSUE THREAD

**Issue by HUGEwindow** [thp/psmoveapi#195]
Note: If this did not work, you might need to build the API step-by-step. See “Building the API manually” for the alternative procedure.

Where can i find this? 

I am trying to pair a move controller with macbook running el capetian 

Thanks in adavance.

**Comment by nitsch** [comment]
It is in the very same document you are quoting.

**Comment by HUGEwindow** [comment]
My apologies. 

This mean anything:
In file included from /Users/open/Dev/psmoveapi/src/platform/psmove_osxsupport.m:33:
In file included from /System/Library/Frameworks/IOBluetooth.framework/Headers/objc/IOBluetoothHostController.h:6:
In file included from /System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:10:
In file included from /System/Library/Frameworks/Foundation.framework/Headers/NSArray.h:6:
/System/Library/Frameworks/Foundation.framework/Headers/NSEnumerator.h:7:15: error: expected ';' after @class
@class NSArray<ObjectType>;
