### ISSUE TITLE
MinGW build broken

### ISSUE THREAD

**Issue by nitsch** [thp/psmoveapi#201]
Commit fe0e46eb5407022fd4a9cb844b765bc3cec7c8fd broke MinGW with the changes in `src/daemon/moved_client.c`. Also see https://github.com/rovarma/psmoveapi/commit/fe0e46eb5407022fd4a9cb844b765bc3cec7c8fd#commitcomment-15644084. The whole moved section probably needs some work.

**Comment by rovarma** [comment]
I've been busy with PS3EYEDriver improvements, but I'll try to get this fixed tonight. Don't have a MingW setup, so need to figure that out first.

**Comment by thp** [comment]
This should be fixed now.
