### ISSUE TITLE
Tracker enhancement - Blinking calibration dims bulb in well-lit rooms

### ISSUE THREAD

**Issue by cboulay** [thp/psmoveapi#208]
As mentioned in #206 , I'm listing off some features in my fork that I hope someone can bring up to the parent repo.

This one is the improvement to the blinking calibration that makes it less sensitive to the room being a little bright. The problem, hinted at in #183 and #150 , is that the blinking calibration will reduce the bulb brightness if the colour is too saturated. This is desirable in low-light with high exposure because bright bulbs of different colour will appear white-ish under high exposure. However, with the bulb being white, in a bright room the bulb will be white-ish (high sat.) and decreasing the LED brightness will make it more white, until eventually it turns off the LED altogether.

[My solution](https://github.com/cboulay/psmoveapi/blob/master/src/tracker/psmove_tracker.c#L1284-L1306) has worked pretty well for me in most conditions but I'm sure this can be improved upon.

**Comment by thp** [comment]
Can you turn your solution into a pull request, and maybe make it optional (configuration option passed in to the tracker)?
