### ISSUE TITLE
Can't get windows 10 x64 to work.

### ISSUE THREAD

**Issue by greasysock** [thp/psmoveapi#222]
I can't seem to get the ps camera working on windows 10.  I've installed the libusb drivers for the camera.

This is what I see when I initially load an example:

![image](https://cloud.githubusercontent.com/assets/3253689/13797289/d1ce93a8-eae2-11e5-9ecc-091f3f3071d2.png)

This is what I see when I run ps3eye_sdl:
![image](https://cloud.githubusercontent.com/assets/3253689/13797327/1227dc7a-eae3-11e5-9dc4-f9bd19b15615.png)

So I know that it's working in a way. 

I can sort of make it work by first running tuio_server and then starting some tests, but it still dosn't work right

![image](https://cloud.githubusercontent.com/assets/3253689/13797353/3c7c04ec-eae3-11e5-9daf-e7f6cf4262b9.png)

Any suggestions?

**Comment by cboulay** [comment]
It's probably a bandwidth issue. ps3eye_sdl uses a low resolution so it doesn't tax the USB channel very much. Try unplugging other USB devices that are plugged in next to the ps eye.

Are you using Zadig to install the libusb drivers? Which version did you install? libusbK, win32, or WinUSB? While they all worked for me on Windows 8 and below, only one worked on Windows 10. I'm away from my Win10 machine right now and I can't remember which. It doesn't take long to try them all. Before you switch to a different driver, be sure to use control panel to uninstall the old one and also delete the driver file when you uninstall it (it's a checkbox option when you uninstall).

**Comment by greasysock** [comment]
I tried every driver in Zadig. Pulled out everything but my keyboard. Discovered that the camera only works right when i have it in a usb 3.1 port. 

Then I fired up a lubuntu VM in virtualbox and passed through the camera and controller, was able to see the camera and run the examples fine. In Guvcview, I can only open up a 50fps stream at 640x480.

**Comment by rovarma** [comment]
I got a new Win10 machine yesterday, so I tried this out. The camera still works fine for me (using libusb-win32), so I'm inclined to agree with @cboulay that this is a hardware issue.

**Comment by thp** [comment]
Closing as hardware issue as per the latest two comments.
