### ISSUE TITLE
Can't get past PSMoveCameraCalibration.exe

### ISSUE THREAD

**Issue by Cman1468** [thp/psmoveapi#229]
Everything has worked properly up until the camera calibration. I installed all of the drivers, and open up the OSVR server with the .json file, but I still get this "no plugin found" error, here's the log: http://imgur.com/O4lmr1e
Do you know why it isn't working? The dll is in the plugin folder. Thanks!

**Comment by cboulay** [comment]
What are you talking about? What instructions did you follow?

**Comment by Cman1468** [comment]
wait, I just realized this the wrong github project. sorry!
