### ISSUE TITLE
Explicitly use OpenCV 2

### ISSUE THREAD

**Issue by nitsch** [thp/psmoveapi#336]
We should use a version from OpenCV's 2.x branch. The C API was deprecated in OpenCV 3.x, and stuff breaks (see #335, #251). Plus, there really is no need to use OpenCV 3. We use non of its features. The 2.x branch is still maintained by OpenCV folks.

If there are mentions of OpenCV 3 in the documentation, they should be replaced. If some of the build scripts either use OpenCV 3 or do not specifically use 2.x, they should be fixed, too.

**Comment by thp** [comment]
Yes, is there any good branch in upstream OpenCV that we could reference?

**Comment by nitsch** [comment]
> Yes, is there any good branch in upstream OpenCV that we could reference?

Sure, branch 2.4 (https://github.com/opencv/opencv/tree/2.4) would be
the one.
