### ISSUE TITLE
Similar colors get mixed up with Facetime calibration (3 controllers)

### ISSUE THREAD

**Issue by SableRaf** [thp/psmoveapi#34]
Colors that are too close get mistaken for one another by the tracker. This is probably due to the exposure lock altering the colors.

See video: https://docs.google.com/open?id=0B4qt2CFBOa6VSlJ1ZHNxNGZPWjg

**Comment by thp** [comment]
Facetime calibration is removed in the current development version. Also, there's some tracker updates coming that should improve things. Closing as fixed / outdated.
