### ISSUE TITLE
raspberry pi error:dynamic module does not define init function

### ISSUE THREAD

**Issue by AvadaX** [thp/psmoveapi#346]
Hi, I bulit the psmove api on my raspberry pi 3 today followed the tutorial [building-for-the-pocket-c-h-i-p](https://psmoveapi.readthedocs.io/en/latest/build.html#building-for-the-pocket-c-h-i-p)

after built the psmoveapi, I run the command:
`/home/pi/psmoveapi/build/example`
the PSmove worked

but when I try to run the python example 
`python /home/pi/psmoveapi/examples/python/psmove_test.py`
it showed an error:

<img width="538" alt="wangwang20180126000456" src="https://user-images.githubusercontent.com/9192125/35398338-907b8416-022c-11e8-80df-5dcca5cd874b.png">

the raspbian system is the latest version
￼￼￼
![wangwang20180125235951](https://user-images.githubusercontent.com/9192125/35398016-ec72c852-022b-11e8-8ce5-7799462e0913.png)
and my python version is 2.7.3

how can I solve this?

**Comment by nitsch** [comment]
Did you follow the [instructions for building Python bindings](https://psmoveapi.readthedocs.io/en/latest/build.html#python-bindings)?

Which version of psmoveapi are you building? Please use the latest release.

**Comment by nitsch** [comment]
@AvadaX Any updates on this?

**Comment by nitsch** [comment]
No response for more than 6 months. Assuming it is either solved or irrelevant now.
