### ISSUE TITLE
Printing Rotation?

### ISSUE THREAD

**Issue by araghuvanshi** [thp/psmoveapi#349]
Hi,
I’m working on a project that requires me to print the location (x,y,z) and the rotation about the x, y and axes. What specific function calls, in python or C, should I use?

**Comment by nitsch** [comment]
Have a look at examples/c/test_opengl.cpp, for example. It uses
psmove_fusion_get_modelview_matrix() and psmove_fusion_get_position().

There is also psmove_get_orientation() which supplies the orientation as
quaternion.
