### ISSUE TITLE
Build error, problem on script 

### ISSUE THREAD

**Issue by Zangetsu38** [thp/psmoveapi#350]
I have try build with script on VS 2017 X64 but not works in alreacdy, patch static for libusb missing part for 2017, and after not found msbuild not idea why.
i have added part for 2017, but not change problem
![image](https://user-images.githubusercontent.com/5261759/37557275-525d73c6-2a02-11e8-96a9-5bd77841445c.png)

**Comment by Zangetsu38** [comment]
ok i have founded why, need use Visual studio command devlopper, but big probleme it is, build with this, modify few file and after git is dirty, maybe need change change, with simple create sln etc, and test on cmake not works, not found opencv not idea why 
![image](https://user-images.githubusercontent.com/5261759/37557607-4cdd30c6-2a07-11e8-9312-15b6a3aca619.png)

**Comment by nitsch** [comment]
I have trouble understanding you. Please upload a log file containing
the console output produced by build_msvc.bat.

Are you building the current master branch from GitHub or any of the
releases (if so, which one)?

**Comment by Zangetsu38** [comment]
It is last master, and i have say after is good compile works with using Visual Studio command, but compile have problem with dirty git, like you see, need improve this system for can compile him without broken/edit file inside git
