### ISSUE TITLE
Replacing git submodules

### ISSUE THREAD

**Issue by nitsch** [thp/psmoveapi#352]
People are trying to build from cloned repositories but often have trouble with submodules (see #332 for example).

We could either add notes everywhere in the documentation (not really likely to be read) or ditch submodules in favor of subtrees. They have the advantage of always delivering *everything* when running a simple `git clone`. No need for additional instructions and command-line options in order to fetch hidapi etc.

What do you think?

**Comment by thp** [comment]
I have no problem making the "small" submodules as subtrees, but the `opencv` submodule is quite big and would make clones a lot bigger (especially for situations where people don't need the tracking features). It would be cool if we could remove or replace the OpenCV dependency altogether.
