### ISSUE TITLE
Unable to see/pair PSMove w/ MicroUSB (CECH-ZCM2J)

### ISSUE THREAD

**Issue by ChainmailBuddha** [thp/psmoveapi#353]
Hello,
I currently have the psmoveapi on a Raspberry Pi 3.
This was built/installed as part of the install of JoustMania (https://github.com/adangert/JoustMania), though I don't believe that is necessarily relevant to the issue I am seeing.

I have several of the newest PSMove controllers (with Micro USB connections), and they do not appear to be detected by or able to be paired by the psmoveapi. I have run **psmove list** and confirmed that my bluetooth adapter (TBW-106UB)  is being detected correctly.  However when I run **psmove pair** it returns the message **"Connected controllers: 0"**

I have confirmed that the controllers are fully charged, and when connected to a Windows 10 computer with the same cable, the controllers are connected and installed as expected.

Are these newest controllers supported by psmoveapi, or am I doing something incorrectly?

**Comment by ChainmailBuddha** [comment]
Doing some more research on this issue, this seems to be a big deal over with the PSMoveService team as well. It would seem that these new controllers have a new PID as well as possible changes to the protocol.
Hopefully this is something that can be resolved, or I need to go and return the 3 pair of new controllers I just picked up... :(

**Comment by nitsch** [comment]
These new controllers are currently not supported by psmoveapi.

And since you have the hardware at your hands: Why don't you try whether
changing the USB product ID works?

**Comment by ChainmailBuddha** [comment]
Sadly, I only acquired the new controllers to work with JoustMania, and since they currently cannot do so, I have returned them and picked up some version 1 controllers which will.
However, I did want to make sure this was on the radar since I had not seen an issue raised yet for it.
I also know some other devs working on the issue now, so hopefully they can get some traction on it.

**Comment by thp** [comment]
I have ordered one of these controllers and can report back once I receive those and have started playing around.

**Comment by thp** [comment]
Also note that not all "PS4" PS Move controllers are actually Micro-USB controllers, some are still repackaged PS3 controllers (Mini-USB), e.g. the ones with "CECH-ZCM1E" as their part number.

As an example, this PS Move "PS4" Controller pack seems to be still the PS3 variant:

![20086283](https://user-images.githubusercontent.com/135241/40839284-24ca81c0-65a2-11e8-8060-ff53090210fd.jpg)

In other words:

 * Supported (same as PS3): CECH-ZCM1E
 * Not (yet) supported (Micro-USB): CECH-ZCM2J

**Comment by thp** [comment]
I now have a CECH-ZCM2J. As a first quick test, updating the PID to the new value lets me set the controllers' color via USB + pair it. Bluetooth connection is unstable, but it might be due to low battery, let's see (currently charging it up, I just received and unpacked it..).

**Comment by cboulay** [comment]
@thp Was the color setting done over USB?

**Comment by nitsch** [comment]
Release 4.0.6 added basic support for CECH-ZCM2.
