### ISSUE TITLE
Automatic build issue OpenCV

### ISSUE THREAD

**Issue by saadminhas** [thp/psmoveapi#357]
Hi,

Facing an issue during the automatic build process by using:

"call scripts/visualc/build_msvc.bat 2017 x64"

It starts the build but errors out during the OpenCV part.

Details below:

.....\VC\Targets\Microsoft.CppCommon.targets(717,5): error MSB6006: "cmd.exe" exited with code 1. [...\external\opencv\build-x64\modules\core\opencv_core.vcxproj]

Help would be appreciated.

Kind Regards,
Saad

**Comment by nitsch** [comment]
This is too little information. Please provide the complete build log
for more details.

**Comment by nitsch** [comment]
No response for half a year. Assuming it is either solved or irrelevant now.
