### ISSUE TITLE
Can't build under fedora

### ISSUE THREAD

**Issue by yeldarb1983** [thp/psmoveapi#358]
[psmove api errors.txt](https://github.com/thp/psmoveapi/files/2100999/psmove.api.errors.txt)
![system info](https://user-images.githubusercontent.com/35431072/41394244-e68d62f2-6f6e-11e8-9996-287e8dfd8834.png)
(edit)I've been trying to compile this under fedora, unfortunately, I can't seem to get all of the packages to build, and so naturally< i'm running into some errors. We spoke recently on youtube, and as you suggested, I'm submitting a bug report. Let me know if you need any other info. thank you again

**Comment by nitsch** [comment]
What version of CMake is this?

**Comment by nitsch** [comment]
I do not have any problem with CMake 3.11.2 on recent Debian and Ubuntu. But I noticed something else in your log: You did not check out the submodules. To do this, either clone wit `git clone --recursive ...` or run `git submodule init && git submodule update` inside the cloned repository to pull the submodules in. I am not exactly sure if this is related to CMake's "No SOURCES given to target" error but worth a try.

**Comment by yeldarb1983** [comment]
Yeah, I'm kind of a babe-in-the-woods when it comes to git... I followed your instructions and got a bit further, though. I still only get to 55% before it errors out. This after updating and rebooting to make sure there wasn't something going on there. At least I can pair the controller and futz around with some of the settings now. That's a start at least. =)

thanks for your help so far, btw. I know dealing with newbs is a pain in the backside, so I really appreciate you taking the time.
[Compile 2.0.txt](https://github.com/thp/psmoveapi/files/2121302/Compile.2.0.txt)

**Comment by nitsch** [comment]
It looks like a problem with the version of OpenCV you are using.
psmoveapi only works with OpenCV 2.x. Build scripts for Windows an Mac
properly retrieve OpenCV 2 but the actual version check in
src/tracker/CMakeLists.txt is missing. The line

  FIND_PACKAGE(OpenCV QUIET)

should rather be

  FIND_PACKAGE(OpenCV 2 QUIET)

If you already have OpenCV 2.x installed this should fix it. If you need
to build it yourself, have a look at scripts/macos/build-macos.

**Comment by yeldarb1983** [comment]
Looks like it's compiling now, and it seems to work for the most part. I'm guessing the compiler is just being fussy about some minor syntax issues? 

At any rate, I got the api up and running, just need to figure out how to get the samples running, and maybe get it to detect the camera (ps3 eye before you ask).

[100% with warnings.txt](https://github.com/thp/psmoveapi/files/2122011/100.with.warnings.txt)

**Comment by nitsch** [comment]
You are building without the tracker right now since no OpenCV could not
be found. If you want to use camera tracking, you need to build with the
tracker enabled.

**Comment by yeldarb1983** [comment]
that's weird, I thought I had it opencv [sigh]. I take it I need to downgrade to opencv 2.0? I think I'm on 3 atm.

**Comment by nitsch** [comment]
Yes, you will have to use OpenCV 2. Some Linux distributions have
dedicated packages for OpenCV 2, so you can install version 3 and 2 side
by side (i.e. no need for a downgrade). Not sure if Fedora does. But
building OpenCV yourself is not too hard either. Especially since
psmoveapi's build script for Mac OS basically contains everything you
need (see my previous posting).

**Comment by nitsch** [comment]
BTW, you do not have to use OpenCV 2.0. Any 2.x is fine.

**Comment by nitsch** [comment]
@yeldarb1983 Any updates on this?

**Comment by yuripourre** [comment]
@yeldarb1983 @nitsch I could build in Fedora 27 using cmake version 3.11.2.
