### ISSUE TITLE
OpenCV Detection issue

### ISSUE THREAD

**Issue by sergds** [thp/psmoveapi#369]
* OS: MacOS 10.13.5
* My OpenCV Version: 3.4.2
* My OpenCV installation: /usr/local
* Detected Path: /Library/Frameworks/Python.framework/Versions/2.7/share/OpenCV
Cmake detects only Python's OpenCV

**Comment by nitsch** [comment]
Are you building from the latest version in Git? If so: CMake is
explicitly looking for OpenCV 2.x only since psmoveapi requires that
version.

**Comment by sergds** [comment]
Thank you, I’ll try to build with OpenCV 2
And will reopen issue if an error will occur
