### ISSUE TITLE
PS Move API doesn't work with the BlueSoleil Bluetooth Driver

### ISSUE THREAD

**Issue by adangert** [thp/psmoveapi#371]
This is what happens when trying to pair with a bluetooth adapter with the BlueSoleil driver on windows.

C:\Users\Aaron\Documents\GitHub\JoustMania\psmoveapi\build-x64>psmove pair
Connected controllers: 1
[PSMOVE WARNING] Magnetometer in e0:ae:5e:4e:7a:c5 not yet calibrated.
PSMove #1 connected via USB.
[PSMOVE WARNING] Failed to find a Bluetooth radioWARNING: Can't determine Bluetooth address.
Make sure Bluetooth is turned on.
[PSMOVE CRITICAL] Assertion fail in psmove_pair: host != NULL
Pairing of #1 failed.
Calibration data available and saved.

**Comment by thp** [comment]
BlueSoleil isn't really supported, please use the Microsoft Bluetooth Stack. Note that you could try pairing with BlueSoleil as well, but you need to pass in the host Bluetooth address manually as parameter after the `pair` command (but nobody has tried, so I'm not sure if BlueSoleil will properly expose the controller as HID device).

**Comment by adangert** [comment]
yeah doesn't seem to work either:

PS C:\Users\Aaron\Documents\GitHub\JoustMania\psmoveapi\build-x64> ./psmove pair 00:15:83:ef:21:55
Using user-supplied host address: 00:15:83:ef:21:55
Connected controllers: 1
[PSMOVE WARNING] Magnetometer in 00:06:f7:1b:dd:e2 not yet calibrated.
PSMove #1 connected via USB.
[PSMOVE WARNING] Failed to find a Bluetooth radioPairing of #1 failed.
Calibration data available and saved.
