### ISSUE TITLE
Build issue Win7 (x64)

### ISSUE THREAD

**Issue by Jickelsen** [thp/psmoveapi#39]
I've run across at least two Windows-specific issues while trying to build. 

http://pastebin.com/hE02FWaf

The first one seems to be related to issues with compilers supplied by MinGW. I've tried both the official version and nuwen's distro http://nuwen.net/mingw.html#install. In the end I just commented the line
<pre> snprintf(result, size, "%02hhx:%02hhx:%02hhx:%02hhx:%02hhx:%02hhx",
             addr[5], addr[4], addr[3], addr[2], addr[1], addr[0]);</pre>
and it worked.

I don't know about the second issue, other than it might be related to the closed issue https://github.com/thp/psmoveapi/issues/37 . Any help would be greatly appreciated!

**Comment by thp** [comment]
Fixed.
