### ISSUE TITLE
failed to build libusb

### ISSUE THREAD

**Issue by ychdxx** [thp/psmoveapi#396]
Apply
![QQ图片20191208224241](https://user-images.githubusercontent.com/50128124/70391076-1a378f80-1a0c-11ea-81e1-e95ac9d863de.png)
please mailme 34120257@QQ.com. thanks, I hope you to help me.

**Comment by nitsch** [comment]
Do the .vcxproj files mentioned in the error message exist in your `external/libusb-1.0/msvc/` subdirectory?

If they don't, you probably did not clone the repository using the `--recursive` option for fetching submodules. You can fix this by running `git submodule init && git submodule update` in your local clone.

**Comment by ychdxx** [comment]
I get,thks,myfriend, you are greate.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Alexander Nitsch"<notifications@github.com&gt;; 
发送时间: 2019年12月8日(星期天) 晚上11:52
收件人: "thp/psmoveapi"<psmoveapi@noreply.github.com&gt;; 
抄送: "叶琮晖"<34120257@QQ.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [thp/psmoveapi] failed to build libusb (#396)




Do the .vcxproj files mentioned in the error message exist in your external/libusb-1.0/msvc/ subdirectory?
 
If they don't, you probably did not clone the repository using the --recursive option for fetching submodules. You can fix this by running git submodule init &amp;&amp; git submodule update in your local clone.

**Comment by ychdxx** [comment]
Hi,my friend,Thanks to your help,but when I reference psmoveapi.dll into c#,there is a error&nbsp; "could not be added,please make sure tha the file is accessible,and that it is a valid assembly or COM component".I need use psmove in unity,best unity4.6.&nbsp;What should I do?.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Alexander Nitsch"<notifications@github.com&gt;; 
发送时间: 2019年12月8日(星期天) 晚上11:52
收件人: "thp/psmoveapi"<psmoveapi@noreply.github.com&gt;; 
抄送: "叶琮晖"<34120257@QQ.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [thp/psmoveapi] failed to build libusb (#396)




Do the .vcxproj files mentioned in the error message exist in your external/libusb-1.0/msvc/ subdirectory?
 
If they don't, you probably did not clone the repository using the --recursive option for fetching submodules. You can fix this by running git submodule init &amp;&amp; git submodule update in your local clone.
