### ISSUE TITLE
How using io.thp.psmove;

### ISSUE THREAD

**Issue by ychdxx** [thp/psmoveapi#397]
my psmove's red led  eventually remain lit .so I reference psmoveapi.dll into c#,there is a error "could not be added,please make sure tha the file is accessible,and that it is a valid assembly or COM component".I need use psmove in unity,best unity4.6. What should I do?

**Comment by nitsch** [comment]
The psmoveapi.dll is not a C# assembly, it is what C# refers to as
"native code". You have to either DllImport and wrap this native library
yourself or use the C# bindings that psmoveapi generates using SWIG.

Check the build log, find the section "Language bindings" and check if
C# bindings are listed as active in the build.

**Comment by ychdxx** [comment]
I downloaded&nbsp;UniMove ,&nbsp; &nbsp; [DllImport("libpsmoveapi")]
&nbsp; &nbsp; private static extern int psmove_count_connected();this return 0.but my psmove's red led eventually remain lit&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Alexander Nitsch"<notifications@github.com&gt;; 
发送时间: 2019年12月14日(星期六) 上午6:17
收件人: "thp/psmoveapi"<psmoveapi@noreply.github.com&gt;; 
抄送: "叶琮晖"<34120257@QQ.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [thp/psmoveapi] How using io.thp.psmove; (#397)



The psmoveapi.dll is not a C# assembly, it is what C# refers to as
 "native code". You have to either DllImport and wrap this native library
 yourself or use the C# bindings that psmoveapi generates using SWIG.
 
 Check the build log, find the section "Language bindings" and check if
 C# bindings are listed as active in the build.

**Comment by ychdxx** [comment]
[DllImport("psmoveapi")]
    private static extern int psmove_count_connected(); DllNotFoundException: E:/test/psmove/UniMove-master4.3/unitypsmove4.6/Assets/Plugins/psmoveapi.dll

**Comment by ychdxx** [comment]
"Language bindings" is default ,I no change everything
