### ISSUE TITLE
libpsmoveapi_tracker.dylib in release

### ISSUE THREAD

**Issue by josuigoa** [thp/psmoveapi#402]
Since this line is commented, the libpsmoveapi_tracer.dylib file is not in the release package. Is it intentional?

https://github.com/thp/psmoveapi/blob/24a3e7bbe11ffcfaa8eb551ca4ba888ef6aeb174/scripts/build_package.sh#L93

**Comment by thp** [comment]
I'm pretty sure there was a good reason for this (https://github.com/thp/psmoveapi/commit/c2382286f266ef43b650128dfa9eff2bf70dd298) but I forgot what it was...
