### ISSUE TITLE
cmake build error on linux ubuntu20.04 about v4l2

### ISSUE THREAD

**Issue by mhw-Parker** [thp/psmoveapi#433]
recently i met a problem when i want to use v4l2 with opencv on ubuntu20.04
here is the problem:
`/usr/bin/ld: CMakeFiles/test0.dir/rmvideocapture.cpp.o: in function `RMVideoCapture::RMVideoCapture(int, int)':
rmvideocapture.cpp:(.text+0x474): undefined reference to `v4l2_open'
/usr/bin/ld: CMakeFiles/test0.dir/rmvideocapture.cpp.o: in function `RMVideoCapture::cOpen(int, int)':
rmvideocapture.cpp:(.text+0xaa9): undefined reference to `v4l2_open'
/usr/bin/ld: CMakeFiles/test0.dir/rmvideocapture.cpp.o: in function `RMVideoCapture::setExposureTime(int)':
rmvideocapture.cpp:(.text+0x1350): undefined reference to `v4l2_set_control'
/usr/bin/ld: CMakeFiles/test0.dir/rmvideocapture.cpp.o: in function `RMVideoCapture::changeVideoFormat(int, int, bool)':
rmvideocapture.cpp:(.text+0x1726): undefined reference to `v4l2_close'
/usr/bin/ld: rmvideocapture.cpp:(.text+0x1736): undefined reference to `v4l2_open'
/usr/bin/ld: CMakeFiles/test0.dir/rmvideocapture.cpp.o: in function `RMVideoCapture::restartCapture()':
rmvideocapture.cpp:(.text+0x1a1c): undefined reference to `v4l2_close'
/usr/bin/ld: rmvideocapture.cpp:(.text+0x1a2c): undefined reference to `v4l2_open'
collect2: error: ld returned 1 exit status`
i have checked the header and the v4l2_open could be found in `#include <libv4l2.h>` 
and the clion can detect v4l2_open
whatever i do it just build failed
i would appreciate that if you can solve this problem, thx!

**Comment by thp** [comment]
Did you install `libv4l-dev`?

**Comment by thp** [comment]
@mhw-Parker Any updates on this?

**Comment by mhw-Parker** [comment]
yes i have installed, i solved it later. thx
