### ISSUE TITLE
Tracker missing in Python bindings for Windows and Linux release 4.0.12

### ISSUE THREAD

**Issue by heretique** [thp/psmoveapi#437]
Hi guys, after struggling to get the latest release working for me (my fault, #436) I've noticed that I couldn't use the tracker module with Python. Is this intentional?
`Environment is Windows 10, Python 3.8, psmoveapi-4.0.12-windows-msvc2017-x64 build`
I suppose that those bindings should be available since there are Python examples using them.
This is what I get when trying to run the `test_tracker.py`:
```
File "e:\Workspace\PythonProjects\TestPsMove\src\test_tracker.py", line 41, in <module>
  tracker = psmove.PSMoveTracker()

builtins.AttributeError: module 'psmove' has no attribute 'PSMoveTracker'
```
Looking inside the `psmove.py` I see that only the `PSMove` class is defined, there's no definition for `PSMoveTracker`

**Comment by nitsch** [comment]
No, this is not intentional. The tracker parts are missing from the Linux and Windows releases. They are present in the macOS release. Seems to be some kind of problem with the automatic CI builds.

**Comment by nitsch** [comment]
@thp Can you look into this? At first glance it seems that the tracker parts in psmove.i guarded with `#ifdef PSMOVE_BUILD_TRACKER` are missing, i.e. passing `PSMOVE_BUILD_TRACKER` into the SWIG build does not work properly. I cannot reproduce this issue locally, but it is happening on the CI server.

**Comment by keops-dev** [comment]
In build_debian I have to add cmake option `-DPSMOVE_BUILD_TRACKER=ON` to build with tracker
