### ISSUE TITLE
Many of the Python Examples have missing parentheses

### ISSUE THREAD

**Issue by SilasStewart** [thp/psmoveapi#439]
In many of the python examples, running them will give errors saying: 
```
  File "/psmoveapi/examples/python/tracker_image_pygame.py", line 54
    print 'Trying to calibrate...'
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Trying to calibrate...')?
```
This is a pretty simple fix to add them, but I can see how working with multiple languages can get hard to get the syntax correct

**Comment by nitsch** [comment]
> This is a pretty simple fix to add them, but I can see how working
> with multiple languages can get hard to get the syntax correct

What are you talking about? This is old Python 2 syntax. That code
simply is rather old.

**Comment by SilasStewart** [comment]
Oh, whoops, I completely missed that! Sorry to bother you.
