### ISSUE TITLE
Cannot compile on m1 Mac

### ISSUE THREAD

**Issue by Marshungry** [thp/psmoveapi#485]
Tried compiling the source code on an M1 Mac but no luck. 

```
(base) arhammahajan@Arhams-MacBook-Pro psmoveapi % bash -e -x scripts/macos/build-macos
+ '[' 0 -eq 0 ']'
+ echo 'Usage: scripts/macos/build-macos [x86_64|arm64]'
Usage: scripts/macos/build-macos [x86_64|arm64]
+ exit 1
```

This is all that happens. Been on it for over a day and can't figure out the problem.

**Comment by thp** [comment]
It says it right there:

```
Usage: scripts/macos/build-macos [x86_64|arm64]
```

You have to pass in either `x86_64` or `arm64` as parameter, depending on whether you have an Intel Mac or an Apple Silicon Mac.

For Intel Macs, use:

```
bash -e -x scripts/macos/build-macos x86_64
```

For Apple Silicon Macs, use:

```
bash -e -x scripts/macos/build-macos arm64
```

**Comment by Marshungry** [comment]
Thank you so much. Finally got it working!!
