### ISSUE TITLE
Pair to Mac on Ventura failures

### ISSUE THREAD

**Issue by ebarben** [thp/psmoveapi#486]
I keep getting failures at the point of Xcode license verification. It appears a bad command is being passed to SSH for the verification. Following are the related log entries:
System.Net.Mqtt.Sdk.MqttClientImpl Information: 0 : Client vs9988ebar - An application message for topic vs9988ebar/response/xvs/idb/get-xcode-location was received: 02/14/2023 19:13:52Z
    DateTime=2023-02-14T19:13:52.0775268Z: 02/14/2023 19:13:52Z
Xamarin.Messaging.Client.MessagingClient Verbose: 0 : Received Response of Xamarin.Messaging.IDB.Contracts.GetXcodeLocationMessage to topic vs9988ebar/+/xvs/idb/get-xcode-location: 02/14/2023 19:13:52Z
    DateTime=2023-02-14T19:13:52.0775268Z: 02/14/2023 19:13:52Z
Xamarin.Messaging.Ssh.SshCommandRunner Verbose: 0 : Executing SSH command '/bin/bash -c 'find "/Applications/Xcode.app/Contents/Developer/usr/bin" -type f | grep xcodebuild''...: 02/14/2023 19:13:52Z
    DateTime=2023-02-14T19:13:52.0856379Z: 02/14/2023 19:13:52Z
Xamarin.Messaging.Ssh.SshCommandRunner Verbose: 0 : Executing SSH command '**"Uptime: 11:13  up  1:38, 1 user, load averages: 3.11 2.55 2.35"** -license check'...: 02/14/2023 19:13:52Z
    DateTime=2023-02-14T19:13:52.1116736Z: 02/14/2023 19:13:52Z
Xamarin.Messaging.Ssh.SshCommandRunner Warning: 0 : Failed to execute '"Uptime: 11:13  up  1:38, 1 user, load averages: 3.11 2.55 2.35" -license check': ExitStatus = 127: 02/14/2023 19:13:52Z
    DateTime=2023-02-14T19:13:52.1235264Z: 02/14/2023 19:13:52Z
Xamarin.Messaging.Ssh.SshCommandRunner Warning: 0 : zsh:1: command not found: Uptime: 11:13  up  1:38, 1 user, load averages: 3.11 2.55 2.35
: 02/14/2023 19:13:52Z
    DateTime=2023-02-14T19:13:52.1245674Z: 02/14/2023 19:13:52Z
Xamarin.Messaging.Ssh.IOSSshCommandsExtensions Error: 0 : An error occurred while checking the Xcode license state on the Mac

I have all the latest components, versions etc. I've disconnected, shut off sharing, rebooted, reenabled sharing, restarted VS 2022, Pair to Mac and still receive the error. I've also removed the XMA(sp?) directory and tried again. Just typing 'uptime' in the mac terminal I do get the text similar to "Uptime: 11:13  up  1:38, 1 user, load averages: 3.11 2.55 2.35" but understandably it is not a valid command. I think "xcodebuild -license check" is, but why is uptime text being returned in the previous command and used for license checks?

Help!

**Comment by thp** [comment]
Does this have anything to do with PS Move API? Seems like your comment is
a generic Visual Studio <-> macOS issue.

Please read the context of issues before posting unrelated support requests
:)

ebarben ***@***.***> schrieb am Di. 14. Feb. 2023 um 20:57:
