### ISSUE TITLE
C# bindings: Exception on "new PSMove()"

### ISSUE THREAD

**Issue by DragoonAethis** [thp/psmoveapi#60]
(Finally) Got C# bindings to compile, and while trying to run LEDs example (tried with .NET 4.5, 4.0, 3.5 and 2.0), "unhandled exception of type 'System.TypeInitializationException' occurred in ConsoleApplication1.exe. Type initializer threw an exception for 'io.thp.psmove.psmoveapi_csharpPINVOKE'."

That happened during `PSMove move = new PSMove();`. Visual Studio points to `public PSMove() : this(psmoveapi_csharpPINVOKE.new_PSMove__SWIG_0(), true) { }`, but I don't know how to fix this. Adding id in constructor doesn't help, either.

The code: https://gist.github.com/DragoonAethis/151a618941cea09ed3ed

**Comment by DoctorZurk** [comment]
Are the c# binding "good" to work with Unity mono c# ? 
What's the path to work with the compiled library (OSX) with Unity ?

**Comment by thp** [comment]
The C# bindings should work now, if not, use the UniMove or any of the other Unity projects out there.
