### ISSUE TITLE
magnetometer_calibration not starting

### ISSUE THREAD

**Issue by SableRaf** [thp/psmoveapi#71]
magnetometer_calibration just hangs there...

![capture decran 2013-06-27 a 16 59 02](https://f.cloud.github.com/assets/290261/716753/aa71dc20-df3c-11e2-992d-3795a5832fb2.jpg)

**Comment by thp** [comment]
Fixed with https://github.com/thp/psmoveapi/commit/944f3fb4a6ad427ca9697df2d73e937e7603c0a6
