### ISSUE TITLE
Magnetometer calibration MINIMUM_REQUIRED_RANGE

### ISSUE THREAD

**Issue by mglanville** [thp/psmoveapi#76]
I've found that the magnetometer range varies substantially with environment. The current setting of 320 means that calibration never completes for me in one part of my office. I've found 240 to be a sensible value there. If I move to other other side of the building 240 is much too low and calibration completes before I've moved the controller through all orientations on each axis. I ended up with 340 in that location.

I don't fully understand how the magnetometer calibration works so I'm not sure what to suggest could be done about this other than manually adjusting the #define as I've been doing. Is it possible to have this calculated dynamically at runtime? Could the user press a button when they think they've rotated the controller enough?

**Comment by thp** [comment]
Apparently fixed with #166
