### ISSUE TITLE
Issue with PsMovePair and connecting via Bluetooth

### ISSUE THREAD

**Issue by hossainiir** [thp/psmoveapi#78]
Hi,
after running the psmovepair i got this message:

Connected controllers: 1
[PSMOVE WARNING] Magnetometer in 00:06:f7:ce:ba:4e not yet calibrated.
PSMove #1 connected via USB.
Pairing of #1 succeeded!
Controller address: 00:06:f7:ce:ba:4e
Calibration data available and saved.

but bluetooth can't detect move!!!!
by MotionInJoy i can pair them and they work fine.

Can u help me??

**Comment by thp** [comment]
No feedback for nearly two years, closing.
