### ISSUE TITLE
Architecture issue in "build-osx-snapshot" while linking against OpenCV on Mac 

### ISSUE THREAD

**Issue by SableRaf** [thp/psmoveapi#97]
```ld: warning: ignoring file /usr/local/lib/libopencv_calib3d.dylib, file was built for unsupported file format ( 0xcf 0xfa 0xed 0xfe 0x 7 0x 0 0x 0 0x 1 0x 3 0x 0 0x 0 0x 0 0x 6 0x 0 0x 0 0x 0 ) which is not the architecture being linked (i386): /usr/local/lib/libopencv_calib3d.dylib```

See https://github.com/thp/psmoveapi/issues/72 for the whole build log.

**Comment by thp** [comment]
Fixed by #96.
